log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

jwt:
  secret_key: 0x...
  access_expiration_time: 12h
  refresh_expiration_time: 24h

cookies:
  domain: "rarime.com"
  secure: true
  same_site: 4

auth_verifier:
  disabled: true

admin:
  disabled: false
  password_hash: 0x...
