on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          cd ./docs
          npm install
          npm run build

      - run: touch docs/.nojekyll
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/web_deploy # The folder the action should deploy.
